logging:
  level:
    org:
#      springframework: DEBUG
      example: TRACE

########## FGA CONFIG #########

### NO AUTH - for example purposes only!! ###
openfga:
  api-url: http://localhost:4000
