name: Checks

on:
  merge_group:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  fossa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Install dependencies
        run: ./gradlew build
      - name: Run FOSSA scan and upload build data
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          branch: ${{ github.ref_name }}
      - name: Run FOSSA tests
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: true

  test:
    name: Run Checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [17, 21]

    steps:
      - name: Checkout the source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@b231772637bb498f11fdbc86052b6e8a8dc9fc92 # v2.1.2
      - name: Set up JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"
      - name: Run Gradle check task
        run: ./gradlew check --continue
